import Head from "next/head";
import Image from "next/image";
import Nav from "components/Nav";
import Hero from "components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SCAPYM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-8xl font-black text-center mt-20 sm:text-5xl md:text-7xl text-transparent bg-clip-text bg-gradient-to-br from-[#d53369] to-[#cbad6d] filter drop-shadow">
        SCAPYM
      </h1>

      {/* Nav */}
      <Nav />

      {/* Hero */}
      <Hero />
    </div>
  );
}
